// Auto-generated exercise library from user list
import type { EjBiblioteca } from "./ejercicios";

export const USER_EXERCISE_LIBRARY: EjBiblioteca[] = [
  { id: 'u001', nombre: '1 Arm Farmers Carry', grupo: 'General' },
  { id: 'u002', nombre: '1 Arm Kneeling Press', grupo: 'General' },
  { id: 'u003', nombre: '1 Arm overhead Hold', grupo: 'General' },
  { id: 'u004', nombre: '1 Arm Power Row', grupo: 'General' },
  { id: 'u005', nombre: '1 Arm Push Press', grupo: 'General' },
  { id: 'u006', nombre: '1 Arm Ring Rows', grupo: 'General' },
  { id: 'u007', nombre: '1 Arm Russian KB Swing', grupo: 'General' },
  { id: 'u008', nombre: '1 Arm Split Press', grupo: 'General' },
  { id: 'u009', nombre: '1 Arm Suitcase Deadlift', grupo: 'General' },
  { id: 'u010', nombre: '1 Arm Waiter Squat', grupo: 'General' },
  { id: 'u011', nombre: '45 back extension', grupo: 'General' },
  { id: 'u012', nombre: '45 back extension single leg', grupo: 'General' },
  { id: 'u013', nombre: '45 back extension smith machine', grupo: 'General' },
  { id: 'u014', nombre: 'Abdominal Mat Sit up', grupo: 'General' },
  { id: 'u015', nombre: 'Alternating Dead Bug', grupo: 'General' },
  { id: 'u016', nombre: 'Alternating Groiners', grupo: 'General' },
  { id: 'u017', nombre: 'Alternating Push Up Shoulder Taps', grupo: 'General' },
  { id: 'u018', nombre: 'assisted pull ups', grupo: 'General' },
  { id: 'u019', nombre: 'Assisted pull ups Smith machine', grupo: 'General' },
  { id: 'u020', nombre: 'australian pull ups', grupo: 'General' },
  { id: 'u021', nombre: 'B stance DB Rdl', grupo: 'General' },
  { id: 'u022', nombre: 'b stance dumbbell ddl', grupo: 'General' },
  { id: 'u023', nombre: 'B stance rdl mid glute bias', grupo: 'General' },
  { id: 'u024', nombre: 'Back Squat', grupo: 'General' },
  { id: 'u025', nombre: 'Ball dumbbell chest press', grupo: 'General' },
  { id: 'u026', nombre: 'Band abd machine', grupo: 'General' },
  { id: 'u027', nombre: 'Band squat jump', grupo: 'General' },
  { id: 'u028', nombre: 'band walk side', grupo: 'General' },
  { id: 'u029', nombre: 'Banded Broad Jump', grupo: 'General' },
  { id: 'u030', nombre: 'Banded Plyo Push Up', grupo: 'General' },
  { id: 'u031', nombre: 'Banded Posterior Ankle Distraction', grupo: 'General' },
  { id: 'u032', nombre: 'Bar isqt stiff', grupo: 'General' },
  { id: 'u033', nombre: 'Barbell back squat', grupo: 'General' },
  { id: 'u034', nombre: 'Barbell back squat low bar', grupo: 'General' },
  { id: 'u035', nombre: 'barbell bench press', grupo: 'General' },
  { id: 'u036', nombre: 'Barbell bent over prone', grupo: 'General' },
  { id: 'u037', nombre: 'Barbell bent over row supine', grupo: 'General' },
  { id: 'u038', nombre: 'Barbell bent over smith machine', grupo: 'General' },
  { id: 'u039', nombre: 'barbell búlgaras', grupo: 'General' },
  { id: 'u040', nombre: 'barbell curtsy lunge', grupo: 'General' },
  { id: 'u041', nombre: 'Barbell deadlift conventional', grupo: 'General' },
  { id: 'u042', nombre: 'Barbell deadlift conventional deficit', grupo: 'General' },
  { id: 'u043', nombre: 'Barbell front squat', grupo: 'General' },
  { id: 'u044', nombre: 'barbell good morning', grupo: 'General' },
  { id: 'u045', nombre: 'Barbell hip thrust', grupo: 'General' },
  { id: 'u046', nombre: 'barbell incline bench press', grupo: 'General' },
  { id: 'u047', nombre: 'barbell lateral lunge', grupo: 'General' },
  { id: 'u048', nombre: 'Barbell Overhead Hold', grupo: 'General' },
  { id: 'u049', nombre: 'Barbell pendlay row', grupo: 'General' },
  { id: 'u050', nombre: 'Barbell rdl', grupo: 'General' },
  { id: 'u051', nombre: 'Barbell rdl b stance', grupo: 'General' },
  { id: 'u052', nombre: 'Barbell rdl deficit', grupo: 'General' },
  { id: 'u053', nombre: 'Barbell rdl single leg', grupo: 'General' },
  { id: 'u054', nombre: 'Barbell rdl stiff leg', grupo: 'General' },
  { id: 'u055', nombre: 'Barbell reverse lunge', grupo: 'General' },
  { id: 'u056', nombre: 'Barbell reverse lunges deficit', grupo: 'General' },
  { id: 'u057', nombre: 'Barbell Rollout', grupo: 'General' },
  { id: 'u058', nombre: 'Barbell split squat', grupo: 'General' },
  { id: 'u059', nombre: 'barbell split squat 45 edge', grupo: 'General' },
  { id: 'u060', nombre: 'Barbell split squat deficit', grupo: 'General' },
  { id: 'u061', nombre: 'Barbell Step ups', grupo: 'General' },
  { id: 'u062', nombre: 'Barbell sumo deadlift', grupo: 'General' },
  { id: 'u063', nombre: 'Barbell sumo deadlift deficit', grupo: 'General' },
  { id: 'u064', nombre: 'barbell sumo squat', grupo: 'General' },
  { id: 'u065', nombre: 'barbell upright row', grupo: 'General' },
  { id: 'u066', nombre: 'barbell z spider curl', grupo: 'General' },
  { id: 'u067', nombre: 'Battle rope', grupo: 'General' },
  { id: 'u068', nombre: 'BB Pogo Jump', grupo: 'General' },
  { id: 'u069', nombre: 'BB Push Press', grupo: 'General' },
  { id: 'u070', nombre: 'bear walk', grupo: 'General' },
  { id: 'u071', nombre: 'Belt Squat', grupo: 'General' },
  { id: 'u072', nombre: 'bench abs leg raises', grupo: 'General' },
  { id: 'u073', nombre: 'bench abs oblique', grupo: 'General' },
  { id: 'u074', nombre: 'bench abs sit up', grupo: 'General' },
  { id: 'u075', nombre: 'bench knee raises', grupo: 'General' },
  { id: 'u076', nombre: 'Bench Knee Tucks', grupo: 'General' },
  { id: 'u077', nombre: 'bench machine chest press', grupo: 'General' },
  { id: 'u078', nombre: 'Bench support dumbbell bent over', grupo: 'General' },
  { id: 'u079', nombre: 'Bench support dumbbell wide row', grupo: 'General' },
  { id: 'u080', nombre: 'Bent Knee Hollow Body Hold', grupo: 'General' },
  { id: 'u081', nombre: 'bent over cable row', grupo: 'General' },
  { id: 'u082', nombre: 'Bent Over Row', grupo: 'General' },
  { id: 'u083', nombre: 'Bird dog', grupo: 'General' },
  { id: 'u084', nombre: 'Body saw', grupo: 'General' },
  { id: 'u085', nombre: 'Body W Row', grupo: 'General' },
  { id: 'u086', nombre: 'booty builder', grupo: 'General' },
  { id: 'u087', nombre: 'booty builder parciales alargamiento', grupo: 'General' },
  { id: 'u088', nombre: 'booty builder single leg', grupo: 'General' },
  { id: 'u089', nombre: 'Bottom of the Burpee', grupo: 'General' },
  { id: 'u090', nombre: 'box barbell squat', grupo: 'General' },
  { id: 'u091', nombre: 'box jump', grupo: 'General' },
  { id: 'u092', nombre: 'box pistol squat', grupo: 'General' },
  { id: 'u093', nombre: 'box squat', grupo: 'General' },
  { id: 'u094', nombre: 'Bret dumbbell mid glute', grupo: 'General' },
  { id: 'u095', nombre: 'bret machine abd', grupo: 'General' },
  { id: 'u096', nombre: 'bulgara doble pulso', grupo: 'General' },
  { id: 'u097', nombre: 'Bulgara side jump', grupo: 'General' },
  { id: 'u098', nombre: 'burpees', grupo: 'General' },
  { id: 'u099', nombre: 'burpees to curl to press', grupo: 'General' },
  { id: 'u100', nombre: 'cable chest press', grupo: 'General' },
  { id: 'u101', nombre: 'cable costal chest press', grupo: 'General' },
  { id: 'u102', nombre: 'Cable crunch', grupo: 'General' },
  { id: 'u103', nombre: 'cable d1', grupo: 'General' },
  { id: 'u104', nombre: 'Cable drag curl', grupo: 'General' },
  { id: 'u105', nombre: 'cable face pull', grupo: 'General' },
  { id: 'u106', nombre: 'cable flexi row', grupo: 'General' },
  { id: 'u107', nombre: 'Cable Front Raises one arm', grupo: 'General' },
  { id: 'u108', nombre: 'cable front raises rope', grupo: 'General' },
  { id: 'u109', nombre: 'Cable Glute KickBack', grupo: 'General' },
  { id: 'u110', nombre: 'Cable hip adduction', grupo: 'General' },
  { id: 'u111', nombre: 'Cable HK Paloff Iso Hold', grupo: 'General' },
  { id: 'u112', nombre: 'cable kass kick press', grupo: 'General' },
  { id: 'u113', nombre: 'cable lateral kick press', grupo: 'General' },
  { id: 'u114', nombre: 'cable lateral kick press bench support', grupo: 'General' },
  { id: 'u115', nombre: 'Cable lateral raises fade away single arm', grupo: 'General' },
  { id: 'u116', nombre: 'Cable lateral raises single arm', grupo: 'General' },
  { id: 'u117', nombre: 'Cable lateral raises single arm back', grupo: 'General' },
  { id: 'u118', nombre: 'cable pec fly', grupo: 'General' },
  { id: 'u119', nombre: 'cable pull around', grupo: 'General' },
  { id: 'u120', nombre: 'cable pull around toracic', grupo: 'General' },
  { id: 'u121', nombre: 'cable pullover', grupo: 'General' },
  { id: 'u122', nombre: 'Cable pullover support', grupo: 'General' },
  { id: 'u123', nombre: 'cable rdl', grupo: 'General' },
  { id: 'u124', nombre: 'cable rotational abs', grupo: 'General' },
  { id: 'u125', nombre: 'cable row one arm support', grupo: 'General' },
  { id: 'u126', nombre: 'cable shoulder press', grupo: 'General' },
  { id: 'u127', nombre: 'cable single arm overhead tricep support', grupo: 'General' },
  { id: 'u128', nombre: 'cable triceps overhead rope', grupo: 'General' },
  { id: 'u129', nombre: 'Cable triceps push down rope', grupo: 'General' },
  { id: 'u130', nombre: 'Cable upper back row', grupo: 'General' },
  { id: 'u131', nombre: 'cable upright row', grupo: 'General' },
  { id: 'u132', nombre: 'cable Y raises', grupo: 'General' },
  { id: 'u133', nombre: 'Calf leg press', grupo: 'General' },
  { id: 'u134', nombre: 'Calf raises', grupo: 'General' },
  { id: 'u135', nombre: 'cambered barbell bench press', grupo: 'General' },
  { id: 'u136', nombre: 'cambered barbell incline bench press', grupo: 'General' },
  { id: 'u137', nombre: 'Cat Camel Rock Back', grupo: 'General' },
  { id: 'u138', nombre: 'Chest Press Machine Technogym', grupo: 'General' },
  { id: 'u139', nombre: 'Chest Supported Row Machine', grupo: 'General' },
  { id: 'u140', nombre: 'Chop and Lift', grupo: 'General' },
  { id: 'u141', nombre: 'clamshells', grupo: 'General' },
  { id: 'u142', nombre: 'clavicular pec fly', grupo: 'General' },
  { id: 'u143', nombre: 'close grip push up', grupo: 'General' },
  { id: 'u144', nombre: 'CMJ MOD', grupo: 'General' },
  { id: 'u145', nombre: 'Contra movimiento CM', grupo: 'General' },
  { id: 'u146', nombre: 'copenague', grupo: 'General' },
  { id: 'u147', nombre: 'Cross cable triceps', grupo: 'General' },
  { id: 'u148', nombre: 'Curl cable bar', grupo: 'General' },
  { id: 'u149', nombre: 'Curl Up', grupo: 'General' },
  { id: 'u150', nombre: 'dead bug', grupo: 'General' },
  { id: 'u151', nombre: 'Deadlift', grupo: 'General' },
  { id: 'u152', nombre: 'decline push ups', grupo: 'General' },
  { id: 'u153', nombre: 'deficit push ups', grupo: 'General' },
  { id: 'u154', nombre: 'Depth Rebound', grupo: 'General' },
  { id: 'u155', nombre: 'dips', grupo: 'General' },
  { id: 'u156', nombre: 'Doble contacto DC', grupo: 'General' },
  { id: 'u157', nombre: 'dragon flag', grupo: 'General' },
  { id: 'u158', nombre: 'Drax High row', grupo: 'General' },
  { id: 'u159', nombre: 'drop jump', grupo: 'General' },
  { id: 'u160', nombre: 'drop jump box', grupo: 'General' },
  { id: 'u161', nombre: 'drop jump reactivo', grupo: 'General' },
  { id: 'u162', nombre: 'dual cable ant delt press', grupo: 'General' },
  { id: 'u163', nombre: 'dual cable curl acortamiento', grupo: 'General' },
  { id: 'u164', nombre: 'dual cable curl alargamiento', grupo: 'General' },
  { id: 'u165', nombre: 'dual cable curls', grupo: 'General' },
  { id: 'u166', nombre: 'Dual cable front raises', grupo: 'General' },
  { id: 'u167', nombre: 'dual cable lateral raises', grupo: 'General' },
  { id: 'u168', nombre: 'dual cable lateral raises fadeaway', grupo: 'General' },
  { id: 'u169', nombre: 'dual cable rear fly', grupo: 'General' },
  { id: 'u170', nombre: 'dual cable upper chest', grupo: 'General' },
  { id: 'u171', nombre: 'dumbbel reverse lunge roller deficit', grupo: 'General' },
  { id: 'u172', nombre: 'Dumbbell Arnold Press', grupo: 'General' },
  { id: 'u173', nombre: 'Dumbbell bench incline curls', grupo: 'General' },
  { id: 'u174', nombre: 'Dumbbell bench incline lateral raises', grupo: 'General' },
  { id: 'u175', nombre: 'dumbbell biceps curls support', grupo: 'General' },
  { id: 'u176', nombre: 'dumbbell bulgaras', grupo: 'General' },
  { id: 'u177', nombre: 'dumbbell bulgaras deficit', grupo: 'General' },
  { id: 'u178', nombre: 'Dumbbell chest press', grupo: 'General' },
  { id: 'u179', nombre: 'Dumbbell chest press single arm', grupo: 'General' },
  { id: 'u180', nombre: 'Dumbbell curls', grupo: 'General' },
  { id: 'u181', nombre: 'dumbbell curtsy lunge', grupo: 'General' },
  { id: 'u182', nombre: 'dumbbell curtsy lunge deficit', grupo: 'General' },
  { id: 'u183', nombre: 'Dumbbell devil press', grupo: 'General' },
  { id: 'u184', nombre: 'Dumbbell front raises', grupo: 'General' },
  { id: 'u185', nombre: 'dumbbell glute bridge band', grupo: 'General' },
  { id: 'u186', nombre: 'Dumbbell Goblet Squat', grupo: 'General' },
  { id: 'u187', nombre: 'dumbbell hammer curl support', grupo: 'General' },
  { id: 'u188', nombre: 'Dumbbell hammer curls', grupo: 'General' },
  { id: 'u189', nombre: 'Dumbbell incline press', grupo: 'General' },
  { id: 'u190', nombre: 'Dumbbell lateral raises', grupo: 'General' },
  { id: 'u191', nombre: 'Dumbbell lateral raises bench chest support', grupo: 'General' },
  { id: 'u192', nombre: 'Dumbbell lateral raises super rom', grupo: 'General' },
  { id: 'u193', nombre: 'dumbbell oblique', grupo: 'General' },
  { id: 'u194', nombre: 'Dumbbell pec fly', grupo: 'General' },
  { id: 'u195', nombre: 'Dumbbell power jump', grupo: 'General' },
  { id: 'u196', nombre: 'Dumbbell preacher curls', grupo: 'General' },
  { id: 'u197', nombre: 'Dumbbell pull over', grupo: 'General' },
  { id: 'u198', nombre: 'dumbbell rdl', grupo: 'General' },
  { id: 'u199', nombre: 'dumbbell rdl single leg', grupo: 'General' },
  { id: 'u200', nombre: 'dumbbell rdl stiff leg', grupo: 'General' },
  { id: 'u201', nombre: 'Dumbbell rear fly', grupo: 'General' },
  { id: 'u202', nombre: 'Dumbbell revers lunge + lateral raises', grupo: 'General' },
  { id: 'u203', nombre: 'Dumbbell reverse lunge', grupo: 'General' },
  { id: 'u204', nombre: 'dumbbell reverse lunge roller', grupo: 'General' },
  { id: 'u205', nombre: 'Dumbbell reverse lunges Deficit', grupo: 'General' },
  { id: 'u206', nombre: 'Dumbbell Seated Alt Shoulder press', grupo: 'General' },
  { id: 'u207', nombre: 'Dumbbell seated shoulder press', grupo: 'General' },
  { id: 'u208', nombre: 'Dumbbell shoulder press single arm', grupo: 'General' },
  { id: 'u209', nombre: 'Dumbbell shoulder press stand', grupo: 'General' },
  { id: 'u210', nombre: 'Dumbbell skull crusher', grupo: 'General' },
  { id: 'u211', nombre: 'Dumbbell spider curls', grupo: 'General' },
  { id: 'u212', nombre: 'dumbbell split edge', grupo: 'General' },
  { id: 'u213', nombre: 'Dumbbell split squat', grupo: 'General' },
  { id: 'u214', nombre: 'Dumbbell split squat deficit', grupo: 'General' },
  { id: 'u215', nombre: 'dumbbell step down', grupo: 'General' },
  { id: 'u216', nombre: 'dumbbell sumo squat deficit', grupo: 'General' },
  { id: 'u217', nombre: 'Dumbbell triceps overhead', grupo: 'General' },
  { id: 'u218', nombre: 'Dumbbell Triceps Skullcrusher', grupo: 'General' },
  { id: 'u219', nombre: 'dumbbell upright row', grupo: 'General' },
  { id: 'u220', nombre: 'dumbbell walking lunges', grupo: 'General' },
  { id: 'u221', nombre: 'dumbbell Y raises', grupo: 'General' },
  { id: 'u222', nombre: 'eccentric hams roller', grupo: 'General' },
  { id: 'u223', nombre: 'eccentric hams roller single leg', grupo: 'General' },
  { id: 'u224', nombre: 'eccentric pull ups', grupo: 'General' },
  { id: 'u225', nombre: 'Elbow on Knee Shoulder external rotation', grupo: 'General' },
  { id: 'u226', nombre: 'fadeaway cable lateral kick', grupo: 'General' },
  { id: 'u227', nombre: 'Farmer walk', grupo: 'General' },
  { id: 'u228', nombre: 'Freemotion back lat', grupo: 'General' },
  { id: 'u229', nombre: 'freemotion dual cable lat pull down', grupo: 'General' },
  { id: 'u230', nombre: 'frog smith', grupo: 'General' },
  { id: 'u231', nombre: 'Front Rack Hold', grupo: 'General' },
  { id: 'u232', nombre: 'front slam wall', grupo: 'General' },
  { id: 'u233', nombre: 'Front Squat', grupo: 'General' },
  { id: 'u234', nombre: 'GHD Iso plate press', grupo: 'General' },
  { id: 'u235', nombre: 'glute bridge single leg', grupo: 'General' },
  { id: 'u236', nombre: 'glute bridge vertice', grupo: 'General' },
  { id: 'u237', nombre: 'goblet squat edge', grupo: 'General' },
  { id: 'u238', nombre: 'Gorila row unilateral', grupo: 'General' },
  { id: 'u239', nombre: 'Hack squat', grupo: 'General' },
  { id: 'u240', nombre: 'Hack squat single leg', grupo: 'General' },
  { id: 'u241', nombre: 'Hack squat sissy squat', grupo: 'General' },
  { id: 'u242', nombre: 'Half Kneeling Cable Row', grupo: 'General' },
  { id: 'u243', nombre: 'Half Kneeling Halo', grupo: 'General' },
  { id: 'u244', nombre: 'Half Kneeling Wall Hip Rotations', grupo: 'General' },
  { id: 'u245', nombre: 'hams roller', grupo: 'General' },
  { id: 'u246', nombre: 'Hang Pull', grupo: 'General' },
  { id: 'u247', nombre: 'hanging knee raises', grupo: 'General' },
  { id: 'u248', nombre: 'hanging leg raises', grupo: 'General' },
  { id: 'u249', nombre: 'High Cable overhead extension', grupo: 'General' },
  { id: 'u250', nombre: 'High Row Machine Hammer Strength', grupo: 'General' },
  { id: 'u251', nombre: 'High Row Machine Technogym', grupo: 'General' },
  { id: 'u252', nombre: 'High row pull around', grupo: 'General' },
  { id: 'u253', nombre: 'hip flexion machine', grupo: 'General' },
  { id: 'u254', nombre: 'Hip Thrust Elite Machine', grupo: 'General' },
  { id: 'u255', nombre: 'hip thrust smith machine', grupo: 'General' },
  { id: 'u256', nombre: 'hk cable pull down one arm', grupo: 'General' },
  { id: 'u257', nombre: 'Hk dumbbell shoulder press', grupo: 'General' },
  { id: 'u258', nombre: 'hk landmine shoulder press', grupo: 'General' },
  { id: 'u259', nombre: 'Hk windmill kettlebell', grupo: 'General' },
  { id: 'u260', nombre: 'hurdles frontal jump', grupo: 'General' },
  { id: 'u261', nombre: 'Hypper en banco rumano', grupo: 'General' },
  { id: 'u262', nombre: 'Inch Worm', grupo: 'General' },
  { id: 'u263', nombre: 'Incline Chest press machine', grupo: 'General' },
  { id: 'u264', nombre: 'incline dumbbell bench row', grupo: 'General' },
  { id: 'u265', nombre: 'incline front raises', grupo: 'General' },
  { id: 'u266', nombre: 'incline push ups', grupo: 'General' },
  { id: 'u267', nombre: 'Ismoetrics squats', grupo: 'General' },
  { id: 'u268', nombre: 'isometric squat whith calf raises', grupo: 'General' },
  { id: 'u269', nombre: 'isometric wall squat', grupo: 'General' },
  { id: 'u270', nombre: 'Jefferson kettlebell', grupo: 'General' },
  { id: 'u271', nombre: 'Jefferson kettlebell deficit', grupo: 'General' },
  { id: 'u272', nombre: 'kass booty builder', grupo: 'General' },
  { id: 'u273', nombre: 'KB Front Rack Carry', grupo: 'General' },
  { id: 'u274', nombre: 'kettlebell rdl shoulder press', grupo: 'General' },
  { id: 'u275', nombre: 'kettlebell swing', grupo: 'General' },
  { id: 'u276', nombre: 'knee jump', grupo: 'General' },
  { id: 'u277', nombre: 'knee push ups', grupo: 'General' },
  { id: 'u278', nombre: 'Kneeling Cable Kick-backs on Bench', grupo: 'General' },
  { id: 'u279', nombre: 'Kneeling Cable Pullover', grupo: 'General' },
  { id: 'u280', nombre: 'kneeling pull around', grupo: 'General' },
  { id: 'u281', nombre: 'landmine curtsy lunge', grupo: 'General' },
  { id: 'u282', nombre: 'Landmine Lateral Lunge', grupo: 'General' },
  { id: 'u283', nombre: 'Landmine Rotational press', grupo: 'General' },
  { id: 'u284', nombre: 'landmine row close grip', grupo: 'General' },
  { id: 'u285', nombre: 'Lat pull down', grupo: 'General' },
  { id: 'u286', nombre: 'Lat pull down lateral unilateral', grupo: 'General' },
  { id: 'u287', nombre: 'lat pull down wide grip', grupo: 'General' },
  { id: 'u288', nombre: 'Lateral Bench Press', grupo: 'General' },
  { id: 'u289', nombre: 'Lateral Hip Banded Distraction', grupo: 'General' },
  { id: 'u290', nombre: 'lateral hip thrust', grupo: 'General' },
  { id: 'u291', nombre: 'Lateral kick cable', grupo: 'General' },
  { id: 'u292', nombre: 'Lateral Leg Swing', grupo: 'General' },
  { id: 'u293', nombre: 'Lateral lunge dumbbell', grupo: 'General' },
  { id: 'u294', nombre: 'Lateral raises one arm 45 bench', grupo: 'General' },
  { id: 'u295', nombre: 'Lateral steps hurdles', grupo: 'General' },
  { id: 'u296', nombre: 'leg extension', grupo: 'General' },
  { id: 'u297', nombre: 'leg extension single leg', grupo: 'General' },
  { id: 'u298', nombre: 'Leg press', grupo: 'General' },
  { id: 'u299', nombre: 'Leg press parciales alargamiento', grupo: 'General' },
  { id: 'u300', nombre: 'Leg press sissy squat', grupo: 'General' },
  { id: 'u301', nombre: 'Leg press sissy squat parciales alargamiento', grupo: 'General' },
  { id: 'u302', nombre: 'Lemon Squeezes', grupo: 'General' },
  { id: 'u303', nombre: 'Loaded Ground Based Bosch Hold', grupo: 'General' },
  { id: 'u304', nombre: 'long jumps', grupo: 'General' },
  { id: 'u305', nombre: 'Low To High Cable Fly', grupo: 'General' },
  { id: 'u306', nombre: 'LP MOB', grupo: 'General' },
  { id: 'u307', nombre: 'lying leg curl machine', grupo: 'General' },
  { id: 'u308', nombre: 'machine add', grupo: 'General' },
  { id: 'u309', nombre: 'Machine calf raises', grupo: 'General' },
  { id: 'u310', nombre: 'Machine calf raises parciales alargamiento', grupo: 'General' },
  { id: 'u311', nombre: 'machine calf raises single leg', grupo: 'General' },
  { id: 'u312', nombre: 'machine decline chest press', grupo: 'General' },
  { id: 'u313', nombre: 'machine kick press single leg', grupo: 'General' },
  { id: 'u314', nombre: 'machine lateral raises', grupo: 'General' },
  { id: 'u315', nombre: 'machine pec fly', grupo: 'General' },
  { id: 'u316', nombre: 'Machine seated flexi row', grupo: 'General' },
  { id: 'u317', nombre: 'Machine seated row', grupo: 'General' },
  { id: 'u318', nombre: 'machine seated shoulder press', grupo: 'General' },
  { id: 'u319', nombre: 'medicine ball woodchopper low', grupo: 'General' },
  { id: 'u320', nombre: 'Mid cable triceps', grupo: 'General' },
  { id: 'u321', nombre: 'Mini hurdles jumps', grupo: 'General' },
  { id: 'u322', nombre: 'Mixed Carry Waiter Overhead', grupo: 'General' },
  { id: 'u323', nombre: 'MOB CE', grupo: 'General' },
  { id: 'u324', nombre: 'Mobility', grupo: 'General' },
  { id: 'u325', nombre: 'Mobility Exercises', grupo: 'General' },
  { id: 'u326', nombre: 'monster walk', grupo: 'General' },
  { id: 'u327', nombre: 'Mountain climbers bench', grupo: 'General' },
  { id: 'u328', nombre: 'No contra movimiento NCM', grupo: 'General' },
  { id: 'u329', nombre: 'nordic', grupo: 'General' },
  { id: 'u330', nombre: 'nordico inverso', grupo: 'General' },
  { id: 'u331', nombre: 'oblique side bends', grupo: 'General' },
  { id: 'u332', nombre: 'One arm dumbbell bent over', grupo: 'General' },
  { id: 'u333', nombre: 'One arm high row', grupo: 'General' },
  { id: 'u334', nombre: 'One Arm Lat Pulldown', grupo: 'General' },
  { id: 'u335', nombre: 'One arm power snatch', grupo: 'General' },
  { id: 'u336', nombre: 'One Arm Rope Tricep Extension', grupo: 'General' },
  { id: 'u337', nombre: 'One arm row polea baja', grupo: 'General' },
  { id: 'u338', nombre: 'overhead tríceps one arm', grupo: 'General' },
  { id: 'u339', nombre: 'Panatta Glute KickBack', grupo: 'General' },
  { id: 'u340', nombre: 'peck fly', grupo: 'General' },
  { id: 'u341', nombre: 'Pendulum squat', grupo: 'General' },
  { id: 'u342', nombre: 'pike roll out', grupo: 'General' },
  { id: 'u343', nombre: 'pistol squat box', grupo: 'General' },
  { id: 'u344', nombre: 'plank', grupo: 'General' },
  { id: 'u345', nombre: 'Plank dumbbell', grupo: 'General' },
  { id: 'u346', nombre: 'Plank Shoulder Taps', grupo: 'General' },
  { id: 'u347', nombre: 'plyo push ups', grupo: 'General' },
  { id: 'u348', nombre: 'Plyo split power jump', grupo: 'General' },
  { id: 'u349', nombre: 'pogos', grupo: 'General' },
  { id: 'u350', nombre: 'Posterior kick press', grupo: 'General' },
  { id: 'u351', nombre: 'press militar', grupo: 'General' },
  { id: 'u352', nombre: 'Prone Leg Curl Machine', grupo: 'General' },
  { id: 'u353', nombre: 'pull ups', grupo: 'General' },
  { id: 'u354', nombre: 'pull ups supine', grupo: 'General' },
  { id: 'u355', nombre: 'Push box', grupo: 'General' },
  { id: 'u356', nombre: 'Push up to Elbow Plank', grupo: 'General' },
  { id: 'u357', nombre: 'push ups', grupo: 'General' },
  { id: 'u358', nombre: 'push ups triceps bias', grupo: 'General' },
  { id: 'u359', nombre: 'QD Rot Ball', grupo: 'General' },
  { id: 'u360', nombre: 'quadruped band kick', grupo: 'General' },
  { id: 'u361', nombre: 'quadruped position + leg extension', grupo: 'General' },
  { id: 'u362', nombre: 'razors', grupo: 'General' },
  { id: 'u363', nombre: 'RDL unilateral', grupo: 'General' },
  { id: 'u364', nombre: 'Rear Fly Machine', grupo: 'General' },
  { id: 'u365', nombre: 'Rear fly one arm', grupo: 'General' },
  { id: 'u366', nombre: 'Rear fly support', grupo: 'General' },
  { id: 'u367', nombre: 'reverse nordic', grupo: 'General' },
  { id: 'u368', nombre: 'Reverse split ski air', grupo: 'General' },
  { id: 'u369', nombre: 'roll out', grupo: 'General' },
  { id: 'u370', nombre: 'Rope Hammer Curl', grupo: 'General' },
  { id: 'u371', nombre: 'Rowing machine', grupo: 'General' },
  { id: 'u372', nombre: 'russian twist', grupo: 'General' },
  { id: 'u373', nombre: 'Sciatic Nerve Flossing', grupo: 'General' },
  { id: 'u374', nombre: 'SDL', grupo: 'General' },
  { id: 'u375', nombre: 'seated barbell militar press', grupo: 'General' },
  { id: 'u376', nombre: 'seated cable chest press', grupo: 'General' },
  { id: 'u377', nombre: 'seated cable incline chest press', grupo: 'General' },
  { id: 'u378', nombre: 'seated cable pec fly', grupo: 'General' },
  { id: 'u379', nombre: 'seated cable row upper back', grupo: 'General' },
  { id: 'u380', nombre: 'Seated Calf Raise Machine', grupo: 'General' },
  { id: 'u381', nombre: 'Seated cuff Lat Raises', grupo: 'General' },
  { id: 'u382', nombre: 'Seated decline pec fly', grupo: 'General' },
  { id: 'u383', nombre: 'Seated dumbbell lateral raises', grupo: 'General' },
  { id: 'u384', nombre: 'seated incline machine abd', grupo: 'General' },
  { id: 'u385', nombre: 'seated leg curl', grupo: 'General' },
  { id: 'u386', nombre: 'seated leg curl single leg', grupo: 'General' },
  { id: 'u387', nombre: 'seated machine abd', grupo: 'General' },
  { id: 'u388', nombre: 'seated machine chest press', grupo: 'General' },
  { id: 'u389', nombre: 'Seated row chest support', grupo: 'General' },
  { id: 'u390', nombre: 'Seoi-Nage Band', grupo: 'General' },
  { id: 'u391', nombre: 'shoulder internal rotation', grupo: 'General' },
  { id: 'u392', nombre: 'Shoulder Press', grupo: 'General' },
  { id: 'u393', nombre: 'side jump cross slam wall', grupo: 'General' },
  { id: 'u394', nombre: 'Side pull down', grupo: 'General' },
  { id: 'u395', nombre: 'single arm dumbbell row - bench', grupo: 'General' },
  { id: 'u396', nombre: 'single arm high cable curl', grupo: 'General' },
  { id: 'u397', nombre: 'single arm push ups', grupo: 'General' },
  { id: 'u398', nombre: 'Single Arm seated Cable Row', grupo: 'General' },
  { id: 'u399', nombre: 'Single calf raises', grupo: 'General' },
  { id: 'u400', nombre: 'Single Leg Alt Deadlift', grupo: 'General' },
  { id: 'u401', nombre: 'Single leg cable rdl', grupo: 'General' },
  { id: 'u402', nombre: 'single leg hip thrust', grupo: 'General' },
  { id: 'u403', nombre: 'Single leg press', grupo: 'General' },
  { id: 'u404', nombre: 'single rdl with row', grupo: 'General' },
  { id: 'u405', nombre: 'sit up slam ball', grupo: 'General' },
  { id: 'u406', nombre: 'skater jumps', grupo: 'General' },
  { id: 'u407', nombre: 'ski erg', grupo: 'General' },
  { id: 'u408', nombre: 'Skipping mini hurdles', grupo: 'General' },
  { id: 'u409', nombre: 'SL Glute Bridge March', grupo: 'General' },
  { id: 'u410', nombre: 'slam ball', grupo: 'General' },
  { id: 'u411', nombre: 'slam ball lateral', grupo: 'General' },
  { id: 'u412', nombre: 'slam wall', grupo: 'General' },
  { id: 'u413', nombre: 'Slingshot Band Setup', grupo: 'General' },
  { id: 'u414', nombre: 'Smith frog pump', grupo: 'General' },
  { id: 'u415', nombre: 'smith machine bench press', grupo: 'General' },
  { id: 'u416', nombre: 'Smith machine bent over flexi row', grupo: 'General' },
  { id: 'u417', nombre: 'Smith machine Bulgaras', grupo: 'General' },
  { id: 'u418', nombre: 'Smith machine Bulgaras deficit', grupo: 'General' },
  { id: 'u419', nombre: 'Smith Machine Calves', grupo: 'General' },
  { id: 'u420', nombre: 'Smith machine edge squat', grupo: 'General' },
  { id: 'u421', nombre: 'Smith machine good morning', grupo: 'General' },
  { id: 'u422', nombre: 'smith machine incline bench press', grupo: 'General' },
  { id: 'u423', nombre: 'Smith Machine Narrow Grip Bench Press', grupo: 'General' },
  { id: 'u424', nombre: 'Smith machine press militar', grupo: 'General' },
  { id: 'u425', nombre: 'Smith machine rdl parcial alargamiento', grupo: 'General' },
  { id: 'u426', nombre: 'Smith machine rdl single leg', grupo: 'General' },
  { id: 'u427', nombre: 'Smith Machine Reverse Glute Kickbacks', grupo: 'General' },
  { id: 'u428', nombre: 'Smith machine reverse lunges', grupo: 'General' },
  { id: 'u429', nombre: 'Smith machine reverse lunges deficit', grupo: 'General' },
  { id: 'u430', nombre: 'Smith Machine Romanian Deadlift', grupo: 'General' },
  { id: 'u431', nombre: 'smith machine shoulder press HK', grupo: 'General' },
  { id: 'u432', nombre: 'Smith machine split squat', grupo: 'General' },
  { id: 'u433', nombre: 'Smith machine split squat deficit', grupo: 'General' },
  { id: 'u434', nombre: 'smith machine split squat quad bias', grupo: 'General' },
  { id: 'u435', nombre: 'Smith machine squat', grupo: 'General' },
  { id: 'u436', nombre: 'smith machine squat bias', grupo: 'General' },
  { id: 'u437', nombre: 'Smith machine step down', grupo: 'General' },
  { id: 'u438', nombre: 'Smith machine sumo squat', grupo: 'General' },
  { id: 'u439', nombre: 'Soleo Machine', grupo: 'General' },
  { id: 'u440', nombre: 'split jumps', grupo: 'General' },
  { id: 'u441', nombre: 'split jumps sissors', grupo: 'General' },
  { id: 'u442', nombre: 'Split Rainbow Slam', grupo: 'General' },
  { id: 'u443', nombre: 'Split Squat Isometric Hold', grupo: 'General' },
  { id: 'u444', nombre: 'Split Squat Rock Back', grupo: 'General' },
  { id: 'u445', nombre: 'split stance landmine shoulder press', grupo: 'General' },
  { id: 'u446', nombre: 'Squat Box Unilateral', grupo: 'General' },
  { id: 'u447', nombre: 'squat jump', grupo: 'General' },
  { id: 'u448', nombre: 'squat to curl to press', grupo: 'General' },
  { id: 'u449', nombre: 'stand band abd', grupo: 'General' },
  { id: 'u450', nombre: 'stand machine abd', grupo: 'General' },
  { id: 'u451', nombre: 'Standing Hip Abductor', grupo: 'General' },
  { id: 'u452', nombre: 'Standing Hip Thrust Machine', grupo: 'General' },
  { id: 'u453', nombre: 'standing leg curl single leg', grupo: 'General' },
  { id: 'u454', nombre: 'Standing Pallof Press', grupo: 'General' },
  { id: 'u455', nombre: 'Step up ball jump', grupo: 'General' },
  { id: 'u456', nombre: 'Step ups', grupo: 'General' },
  { id: 'u457', nombre: 'stir sit the pot', grupo: 'General' },
  { id: 'u458', nombre: 'straight Arm Pulldown', grupo: 'General' },
  { id: 'u459', nombre: 'straight bar tríceps pushdown', grupo: 'General' },
  { id: 'u460', nombre: 'Strict Toes to Bar', grupo: 'General' },
  { id: 'u461', nombre: 'Sumo box squat', grupo: 'General' },
  { id: 'u462', nombre: 'Sumo Deadlift', grupo: 'General' },
  { id: 'u463', nombre: 'Sumo Deadlift Dumbbells', grupo: 'General' },
  { id: 'u464', nombre: 'Sumo Dumbbell Squat', grupo: 'General' },
  { id: 'u465', nombre: 'sumo dumbbell squat pulse', grupo: 'General' },
  { id: 'u466', nombre: 'Sumo Landmine rdl', grupo: 'General' },
  { id: 'u467', nombre: 'Supinated Deadlift Hold', grupo: 'General' },
  { id: 'u468', nombre: 'Supinated Grip Hang', grupo: 'General' },
  { id: 'u469', nombre: 'supine lat pulldown', grupo: 'General' },
  { id: 'u470', nombre: 'Support bench cable row', grupo: 'General' },
  { id: 'u471', nombre: 'Swing americano', grupo: 'General' },
  { id: 'u472', nombre: 'Swing americano unilateral', grupo: 'General' },
  { id: 'u473', nombre: 'Swiss ball crunches', grupo: 'General' },
  { id: 'u474', nombre: 'T row', grupo: 'General' },
  { id: 'u475', nombre: 'T row upper back', grupo: 'General' },
  { id: 'u476', nombre: 'Tall kneeling hip hinge', grupo: 'General' },
  { id: 'u477', nombre: 'The Clean', grupo: 'General' },
  { id: 'u478', nombre: 'Thoracic Extension Rotation', grupo: 'General' },
  { id: 'u479', nombre: 'Thruster shoulder press', grupo: 'General' },
  { id: 'u480', nombre: 'tibials machine', grupo: 'General' },
  { id: 'u481', nombre: 'towel back extension', grupo: 'General' },
  { id: 'u482', nombre: 'Trap bar deadlift', grupo: 'General' },
  { id: 'u483', nombre: 'Trap bar deadlift b stance', grupo: 'General' },
  { id: 'u484', nombre: 'trap bar deadlift deficit', grupo: 'General' },
  { id: 'u485', nombre: 'trap bar rdl', grupo: 'General' },
  { id: 'u486', nombre: 'Trap bar squat deficit', grupo: 'General' },
  { id: 'u487', nombre: 'trap bar squat jump', grupo: 'General' },
  { id: 'u488', nombre: 'triceps bench dips', grupo: 'General' },
  { id: 'u489', nombre: 'Triceps cable one arm medial head', grupo: 'General' },
  { id: 'u490', nombre: 'Turkish Sit up', grupo: 'General' },
  { id: 'u491', nombre: 'unilateral hipthrust', grupo: 'General' },
  { id: 'u492', nombre: 'Wall ball', grupo: 'General' },
  { id: 'u493', nombre: 'wide pull ups', grupo: 'General' },
  { id: 'u494', nombre: 'z barbell curls', grupo: 'General' },
  { id: 'u495', nombre: 'z barbell skull crushers', grupo: 'General' },
  { id: 'u496', nombre: 'z barbell walking lung', grupo: 'General' },
];
